# Workflow para construir e publicar o site no GitHub Pages
name: Deploy Vite site to Pages

on:
  # Executa sempre que fizer um push para a branch `main`
  push:
    branches: [main]
  # Permite executar este workflow manualmente a partir da aba Actions no GitHub
  workflow_dispatch:

# Define permissões para o token do workflow para permitir o deploy
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy de cada vez
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build # Este comando executa "vite build" e cria a pasta 'dist'
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Carrega o conteúdo da pasta 'dist' gerada pelo build
          path: ./dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4